Dp/5 build UI scaffold for student card on dashboard
gschool-blue-ocean/admissions-hub-20 pull request #21
Opened 2023-06-09 00:37 UTC by DanielPurdy509

Student Card built it out with mock hard-coded data + some styling, added to dashboard
<img width="202" alt="Blue_Ocean_Student_Card_Component" src="https://github.com/gschool-blue-ocean/admissions-hub-20/assets/125397922/20309e92-2876-446e-93d5-4a833406bca6">

2023-06-09 08:54 UTC, ranegray commented on client/src/components/StudentCard.jsx
> +                    <li className={StudentCardCSS.studentInfo}>Technical Interview Data: <b>{studentData.interviewDate}</b></li>
This should be technical interview date.

2023-06-09 09:52 UTC, ranegray requested changes
As a general note, lets colocate CSS with our components. 

Create a new folder for StudentCard which will have StudentCard.jsx and StudentCard.module.css

There will be no CSS folder going forward.

2023-06-09 09:52 UTC, ranegray commented on client/src/components/StudentCard.jsx
> +import StudentCardCSS from "../css/StudentCard.module.css";
Let's use object destructuring for cleaner JSX.

e.g. import { cardContainer, studentInfoCard, studentInfo, etc... } from <CSS FILE>

2023-06-09 09:52 UTC, ranegray commented on client/src/components/StudentCard.jsx
> +    }
What if we made a status tag component that we can use on the card and in the table.

We can move this logic into that and all the CSS classes from the module to a new module for better reusability.

Let me know if you have any questions.

2023-06-09 15:55 UTC, jordan-carlson99 commented on client/src/components/StudentCard.jsx
> +        }
what would that look like for the database? csv? or should we consider making another table or column within users

2023-06-09 23:33 UTC, DanielPurdy509 commented
Summary of new changes:
- Reorganized components into folders with corresponding CSS files
- Created StatusTag component for use in the Student Card and elsewhere it is appropriate
- Refactored CSS stylings as requested 
- Changed the names of some of the student info properties as requested

2023-06-13 18:27 UTC, ranegray approved these changes

2023-06-13 18:27 UTC, merged